#!/bin/sh

# Copyright (C) 2020 David Alfonso
#
# This file is part of yadsn.
#
# yadsn is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# yadsn is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with yadsn.  If not, see <https://www.gnu.org/licenses/>.

sn="$(dirname "$(dirname "$0")")/yadsn"

#shellcheck source=yadsn
. "$sn"

setup() {
	mkdir -p "$ts_test_dir"
	cd "$ts_test_dir" || error "unable to enter test directory"
}

teardown() {
	rm -r "$ts_test_dir"
}

error() {
	echo "Error: $1"
	exit 1
}

test_create() {
	file_create "test"
	assert_status 0 $?
	find . -type f | wc -l | assert_output "\
1
"
}

test_text_export_doublequotes_escaped() {
	text_export "Hello\"all!" | assert_output "\
Hello\"\"all!
"
}

test_text_export_newlines() {
	printf "Hello\nall\n!" | assert_output "\
Hello
all
!"
	text_export "Hello
all
!" | assert_output "\
Hello<NEWLINE>all<NEWLINE>!
"
}

test_file_append_simple() {
	file_create "test"
	file_append "test" "one field and line"
	assert_output "\
\"one field and line\"
" < "test"
}

test_file_append_multiline() {
	file_create "test"
	file_append "test" "one line
another line"
	assert_output "\
\"one line<NEWLINE>another line\"
" < "test"
}

test_file_append_multifield() {
	file_create "test"
	file_append "test" "field 1" "another field"
	assert_output "\
\"field 1\",\"another field\"
" < "test"
}

test_file_append_full() {
	file_create "test"
	file_append "test" "field \"1\"" "another field" "third with
multiple
lines"
	assert_output "\
\"field \"\"1\"\"\",\"another field\",\"third with<NEWLINE>multiple<NEWLINE>lines\"
" < "test"
}

test_text_import() {
	text_import "Hello<NEWLINE>all" | assert_output "\
Hello
all
"
	text_import "Hello<NEWLINE>all<NEWLINE>" | assert_output "\
Hello
all

"
	text_import "Hello\"\"all\"\"" | assert_output "\
Hello\"all\"
"
}


export TS_COLOR="true"
#export TS_DEBUG="true"

. tests/ts
